name = "LibDeflate"
uuid = "9255714d-24a7-4b30-8ea3-d46a97f7e13b"
version = "1.0.0"
authors = ["Jakob Nybo Andersen <jnandersen@proton.me>"]

[deps]
libdeflate_jll = "46979653-d7f6-5232-b59e-dd310c4598de"

[compat]
julia = "1.12"
libdeflate_jll = "1"

[workspaces]
projects = ["docs", "test"]
